version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: deploy/php/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dockerApp"
    ports:
      - "33061:3306"

  # composer:
  #   image: composer/composer:alpine